### ISSUE TITLE
[Request]  WotLK Support

### ISSUE THREAD

**Issue by Kolmarwow** [Zsargul/SkillUpProbability#2]
Are there any plans to update this for WotLK Classic by any chance?

**Comment by Zsargul** [comment]
Yes, however it's hard to say when that'll come around because I'm currently busy with other things so it's hard to find the time to work on it.

**Comment by Zsargul** [comment]
I finally ended up updating it. Sorry for the long wait. The updated WOTLK add-on is on [curseforge](https://www.curseforge.com/wow/addons/skillupprobability/files/4068078).
